### ISSUE TITLE
teleporting does not close the connection

### ISSUE THREAD

**Issue by choke-dev** [yafyz/synx-ws-serv#1]
when i teleport / rejoin a server, vscode's console constantly spams "New user tried to connect while one is already connected, rejected."

**Comment by yafyz** [comment]
hmmm, on teleport lua everything should get reset, sounds like synapse is leaking the WS connection
and it has not happened before to me so its probably a new bug
will try to look into it once i get home

**Comment by choke-dev** [comment]
issue resolved after synapse update v2.15.7 was released.
